version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test: # name for job
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm build
            - run: npm test
  deploy: #  name for job
    docker:
      - image: docker:19.03.8 #circleci/node
    working_directory: ~/circleci-demo-workflows
    environment:
      FULL_IMAGE_NAME: "kingbike/mongoosecrud" 
    steps:
      - checkout
      - setup_remote_docker
      - add_ssh_keys:
          fingerprints:
            - "e2:6b:b4:da:35:1c:d8:da:ee:e4:b7:a9:79:51:08:77"
      - run:
          name: Build image
          command: |
            docker build -t $FULL_IMAGE_NAME .
            mkdir docker-image
            docker save -o docker-image/image.tar $FULL_IMAGE_NAME
      - run:
          name: Test image
          command: |
            docker run -d -p 8080:8080 --name built-image $FULL_IMAGE_NAME
            sleep 10
            docker run --network container:built-image byrnedo/alpine-curl -I --retry 10 --retry-connrefused http://localhost:8080
      - run:
          name: Push image
          command: |
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker push $FULL_IMAGE_NAME
      - run:
          name: Deploy Over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST "docker pull $FULL_IMAGE_NAME"
    
workflows:
    build-and-test: # name for workflows
      jobs:
        - build-and-test
        - deploy:
            requires:
              - build-and-test

#production:
#  branch: master # 當修改合進master時即會自動部署
#  - run:
#    name: Deploy Over SSH
#    command: |
#      ssh $SSH_USER@$SSH_HOST "<remote deploy command>"

#production:
#  branch: master # 當修改合進master時即會自動部署
#  commands:
#    - eb use env-prod --profile default 
#    - eb deploy --profile default