version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test: # name for job
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm build
            - run: npm test
  deploy: #  name for job
    docker:
      - image: docker:19.03.8 #circleci/node
    working_directory: ~/circleci-demo-workflows
    environment:
      FULL_IMAGE_NAME: "kingbike/mongoosecrud" 
    steps:
      - checkout
      - setup_remote_docker
      - add_ssh_keys:
          fingerprints:
            - "1e:f1:e8:f4:54:c5:f0:a5:bf:ad:45:81:9c:e8:dd:0c"
      #- run: ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
      #- run: echo '220.135.156.91 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBPsIqQc8jaWQPTFu+EXas9M+Jvh3QBikc0znN9SIGDcdqCLTwfQt+kO3O0YkFp1HAxJ56ZKg+0UvlnCscOQwyWM=' >> ~/.ssh/known_hosts
      - run:
          name: Build image
          command: |
            docker build -t $FULL_IMAGE_NAME .
            mkdir docker-image
            docker save -o docker-image/image.tar $FULL_IMAGE_NAME
      - run:
          name: Test image
          command: |
            docker run -d -p 8888:8888 --name built-image $FULL_IMAGE_NAME
            sleep 10
            docker run --network container:built-image byrnedo/alpine-curl -I --retry 10 --retry-connrefused http://localhost:8888
      - run:
          name: Push image
          command: |
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker push $FULL_IMAGE_NAME
      - run:
          name: Deploy Over SSH
          command: |
            ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "docker pull $FULL_IMAGE_NAME;  docker run -e DB_HOST=192.168.66.129 --name moongose -d -p 8888:8888 $FULL_IMAGE_NAME; "
      #docker run --name mongodb -v /home/jerry/mongodb/data:/data/db -d -p 27017:27017 mongo;
    
workflows:
    build-and-test: # name for workflows
      jobs:
        - build-and-test
        - deploy:
            requires:
              - build-and-test

#production:
#  branch: master # 當修改合進master時即會自動部署
#  commands:
#    - eb use env-prod --profile default 
#    - eb deploy --profile default