version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test: # name for job
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm build
            - run: npm test
  deploy: #  name for job
    docker:
      - image: docker:19.03.8 #circleci/node
    working_directory: ~/circleci-demo-workflows
    environment:
      FULL_IMAGE_NAME: "kingbike/mongoosecrud" 
    steps:
      - checkout
      - setup_remote_docker
      - add_ssh_keys:
          fingerprints:
            - $SSH_KEY
      #- run: ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
      - run:  # build image with ~/Dockerfile
          name: Build image
          command: |
            docker build -t $FULL_IMAGE_NAME .
            mkdir docker-image
            docker save -o docker-image/image.tar $FULL_IMAGE_NAME
      - run:
          name: Test image
          command: |
            docker run -d -p 8888:8888 --name built-image $FULL_IMAGE_NAME
            sleep 10
            docker run --network container:built-image byrnedo/alpine-curl -I --retry 10 --retry-connrefused http://localhost:8888
      - run:
          name: Push image
          command: |
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker push $FULL_IMAGE_NAME
      - run:
          name: Deploy Over SSH
          command: |
            ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "docker pull $FULL_IMAGE_NAME; echo "rm container"; docker rm -f moongose; echo "run container"; docker run -e DB_HOST=192.168.66.130 --name moongose -d -p 8888:8888 $FULL_IMAGE_NAME; "
    
workflows:
    build-and-test: # name for workflows
      jobs:
        - build-and-test
        - deploy:
            requires:
              - build-and-test
            #filters:
            #  branches:
            #    only: master # 當修改合進master時才會自動部署

